name: create-pull-request workflow
on:
  repository_dispatch:
    types: [create-pull-request-multi]
jobs:
  createPullRequest:
    name: Testing on ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Create report file
        if:  matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: date +%s > report.txt
      - name: Create report file (windows)
        if:  matrix.platform == 'windows-latest'
        run: echo %DATE% %TIME% > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@multi-platform-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Add report file
          COMMIT_AUTHOR_EMAIL: peter-evans@users.noreply.github.com
          COMMIT_AUTHOR_NAME: Peter Evans
          PULL_REQUEST_TITLE: '[Example] Add report file'
          PULL_REQUEST_BODY: |
            New report
            - Contains *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          PULL_REQUEST_LABELS: report, automated pr
          PULL_REQUEST_ASSIGNEES: peter-evans
          PULL_REQUEST_REVIEWERS: peter-evans
          PULL_REQUEST_MILESTONE: 1
          PULL_REQUEST_BRANCH: example-patches
          BRANCH_SUFFIX: 'random'
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
