name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    required: true
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
  issue-number:
    description: 'The number of the issue or pull request in which to create a comment.'
  comment-id:
    description: 'The id of the comment to update.'
  body:
    description: 'The comment body.'
  edit-mode:
    description: 'The mode when updating a comment, "replace" or "append".'
  reaction-type:
    description: 'The reaction to add to the comment.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'
