name: 'Release Assets'
description: 'Attach assets to GitHub Release'
author: 'Cloud Posse <hello@cloudposse.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'activity'
  color: 'blue'
