github/auto-approve: github/auto-approve/**
github/auto-assign: github/auto-assign/**
github/auto-merge: github/auto-merge/**
github/branch-cleanup: github/branch-cleanup/**
github/create-pull-request: github/create-pull-request/**
github/git-push: github/git-push/**
github/release-assets: github/release-assets/**
go/build: go/build/**
