name: 'Create Codefresh pipelines'
description: 'GitHub Action that creates Codefresh pipelines from templated spec files'
author: 'Cloud Posse <hello@cloudposse.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'activity'
  color: 'green'
