name: 'Git Push'
description: 'Push Changes to Origin'
author: 'Cloud Posse <hello@cloudposse.com>'
runs:
  using: 'docker'
  image: 'github/git-push/Dockerfile'
branding:
  icon: 'activity'
  color: 'blue'
