name: 'Auto Approve'
description: 'Automatically approve pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
