descriptor_id: EDITORCONFIG
descriptor_type: tooling_format
descriptor_flavors:
  - all_flavors # Applicable to CI in any language project
file_extensions:
  - "*"
active_only_if_file_found:
  - ".editorconfig"
test_folder: editorconfig-checker
linters:
  # EDITORCONFIG-CHECKER
  - linter_name: editorconfig-checker
    linter_url: https://editorconfig-checker.github.io/
    linter_repo: https://github.com/editorconfig-checker/editorconfig-checker
    linter_banner_image_url: https://raw.githubusercontent.com/editorconfig-checker/editorconfig-checker/master/docs/logo.png
    linter_rules_configuration_url: https://github.com/editorconfig-checker/editorconfig-checker#configuration
    linter_rules_inline_disable_url: https://github.com/editorconfig-checker/editorconfig-checker#excluding
    linter_megalinter_ref_url: https://github.com/editorconfig-checker/editorconfig-checker#mega-linter
    config_file_name: .ecrc
    cli_config_arg_name: "-config"
    cli_version_arg_name: "-version"
    linter_version_cache: "0.0.0" # editorconfig-checker -version should work but seems to do not
    examples:
      - "editorconfig-checker myfile.js"
    install:
      npm:
        - editorconfig-checker
