name: Create Comment
on:
  push:
    branches:
      - master
jobs:
  createComment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # For debugging purposes. Remove this in production.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create comment
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown**
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reaction-type: '+1'
