name: Assign reviewers
on:
  repository_dispatch:
    types: [assign-reviewers-command]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:

      - name: Assign reviewers
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_BOT_TOKEN}}
          script: |

            console.log('Executing Assign reviewers script');

            const creator = '${{ github.event.client_payload.pull_request.user.login }}';
            const issueNumber = ${{ github.event.client_payload.pull_request.number }};
            const owner = '${{ github.event.client_payload.pull_request.head.repo.owner.login }}';
            const repo = '${{ github.event.client_payload.pull_request.head.repo.full_name }}';

            const all_reviewers = ['osterman', 'aknysh', 'goruha'];

            // Exclude the PR author from the reviewer list
            const reviewers = all_reviewers.filter((val) => val !== creator);

            await github.pulls.createReviewRequest({
              pull_number: issueNumber,
              owner: owner,
              repo: repo,
              reviewers: reviewers
            });

            await github.issues.addAssignees({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              assignees: [creator]
            });

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
