name: Assign labels
on:
  repository_dispatch:
    types: [assign-labels-command]

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:

      - name: Assign labels
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_BOT_TOKEN}}
          script: |

            console.log('Executing Assign labels script');

            const issueNumber = ${{ github.event.client_payload.pull_request.number }};
            const owner = '${{ github.event.client_payload.pull_request.head.repo.owner.login }}';
            const repo = '${{ github.event.client_payload.pull_request.head.repo.full_name }}';

            const changedFilesResponse = await github.pulls.listFiles({
              pull_number: issueNumber,
              owner: owner,
              repo: repo
            });

            // Max length of labels is 50 chars
            const changedFiles = changedFilesResponse.data.map(f => f.filename.substring(f.filename.length - 50));

            await github.issues.addLabels({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              labels: [...changedFiles]
            });

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
