name: Assign reviewers
on:
  repository_dispatch:
    types: [assign-reviewers-command]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:

      - name: Assign reviewers
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_BOT_TOKEN}}
          script: |

            const reviewers = [
                                'osterman',
                                'aknysh',
                                'goruha'
                              ].filter((val) => val !== '${{ github.event.client_payload.pull_request.user.login }}');

            await github.pulls.createReviewRequest({
              pull_number: ${{ github.event.client_payload.pull_request.number }},
              owner: ${{ github.event.client_payload.pull_request.head.repo.owner.login }},
              repo: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
              reviewers: reviewers
            });

            await github.issues.addAssignees({
              issue_number: ${{ github.event.client_payload.pull_request.number }},
              owner: ${{ github.event.client_payload.pull_request.head.repo.owner.login }},
              repo: ${{ github.event.client_payload.pull_request.head.repo.full_name }},
              assignees: ['${{ github.event.client_payload.pull_request.user.login }}']
            });

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
