name: Assign labels
on:
  repository_dispatch:
    types: [assign-labels-command]

jobs:
  assign-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_BOT_TOKEN }}
          configuration-path: '.github/assign-labels.yml'

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
