name: First interaction greet
on:
  repository_dispatch:
    types: [first-interaction-greet-command]

jobs:
  rebuild_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_BOT_TOKEN }}
          issue-message: |-
            Thank you for reporting the issue! If you haven't already [joined our slack community](https://slack.sweetops.com), then we invite you to do so.

            This is a great place to get help and ask questions from our AMAZING community.

            [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)
          pr-message: |-
            Thank you for submitting this PR! If you haven't already [joined our slack community](https://slack.sweetops.com), then we invite you to do so.

            We receive an overwhelming number of contributions. By joining our slack, we'll be able to review your PR faster.

            [![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

      # Add reaction to the original comment
      - name: Add reaction to the original comment
        uses: cloudposse/actions/github/create-or-update-comment@0.11.0
        with:
          token: ${{ secrets.GITHUB_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
